### ISSUE TITLE
Graphical Bug in MainFrame

### ISSUE THREAD

**Issue by TheGreatBabushka** [AlexFinney/HelpLabTeam6_FinalProject#2]
To repro:
   Click a combo box on the right panel, then click a combo box on the left panel.  Observe that the vertical line becomes broken.  No idea why this is happening, and haven't really looked into yet.  Not a huge issue though

**Comment by S1lverTongue** [comment]
Added borders to the panels, so the "line" doesn't disappear anymore; if we want to go back to the 2D lines, the code is currrently still there, so we can just uncomment some lines.
