### ISSUE TITLE
XML Error and mail.jar

### ISSUE THREAD

**Issue by S1lverTongue** [AlexFinney/HelpLabTeam6_FinalProject#3]
Getting an XML error. Opened up in notepad++ and it showed an error at the

<<<<<<<< HEAD

line. I turned the <'s into >'s and the error disappeared. May need to look at it again though.

Also, I can't build the project because the mail.jar is nowhere to be found.

**Comment by TheGreatBabushka** [comment]
What file was the XML error in?

As for the mail.jar, this is why we really should have done a Maven project haha.

It can be found at: http://www.oracle.com/technetwork/java/javamail/javamail145-1904579.html

Download, extract, put the mail.jar in the lib folder, and add the jar to the build path in your project.
